name: rwheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Conan
      run: pip install conan

    - name: Install Conan dependencies
      run: |
        cd rchp
        conan profile detect --force
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          conan install . --build=missing -s compiler="msvc" -s compiler.version=193 -s compiler.runtime="dynamic"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          conan install . --build=missing -s compiler="apple-clang"
        else
          conan install . --build=missing -s compiler="gcc"
        fi
      shell: bash

    - name: Build wheel
      run: |
        pip install build wheel scikit-build-core pybind11
        python -m build --wheel

    - name: Save wheels
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl
        retention-days: 7
