name: rwheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13","3.14"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install vcpkg and cpr
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        
        if [ "$RUNNER_OS" = "Windows" ]; then
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install cpr:x64-windows
          VCPKG_PATH="$GITHUB_WORKSPACE/vcpkg"
          echo "VCPKG_PATH=$VCPKG_PATH" >> $GITHUB_ENV
          echo "CMAKE_TOOLCHAIN_FILE=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
        else
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install cpr
          VCPKG_PATH="$GITHUB_WORKSPACE/vcpkg"
          echo "VCPKG_PATH=$VCPKG_PATH" >> $GITHUB_ENV
          echo "CMAKE_TOOLCHAIN_FILE=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build wheel
      run: |
        pip install "scikit-build-core>=0.10.0" build wheel pybind11
        cd rchp
        python -m build --wheel --outdir ../dist
      shell: bash

    - name: Repair Linux wheels
      if: runner.os == 'Linux'
      run: |
        pip install auditwheel
        cd dist
        
        for wheel in *.whl; do
          if [[ "$wheel" == *linux_x86_64.whl ]]; then
            echo "Repair $wheel"
            auditwheel repair "$wheel" --plat manylinux_2_28_x86_64 -w .
            rm "$wheel"
          fi
        done
      shell: bash

    - name: Save wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl
        retention-days: 7
